python-server/pomodoro/menu/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pomodoro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r"^ticket/", include("ticket.urls")),
]

python-server/pomodoro/pomodoro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pomodoro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r"^$", "pomodoro.views.home", name="home"),
	url(r"^accounts/login/$","pomodoro.views.login",name="login"),
	url(r"^accounts/logout/$","pomodoro.views.logout",name="logout"),
    url(r"^root/", include(admin.site.urls)),
    url(r"^ticket/", include("ticket.urls",namespace="ticket")),
]

python-server/pomodoro/ticket/urls.py
from django.conf.urls import include, url
from ticket import views
from ticket import tickets

urlpatterns = [
	url(r"^ping/",views.ping,name="ping-pong"),
	url(r"^home/",views.home,name="home"),

	url(r"^$",tickets.find,name="find-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/$",tickets.show,name="show-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/child/$",tickets.addChild,name="add-child-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/interact/$",tickets.addAction,name="add-action-ticket"),
	url(r"^new/$",tickets.new,name="new-ticket"),

	url(r"^action/(?P<actionId>[0-9]+)/$",views.showAction,name="show-action"),
	url(r"^action/new/$",views.newAction,name="new-action"),
	url(r"^author/(?P<authorName>[a-zA-Z0-9]+)/$",views.showAuthor,name="show-author"),
]

python-server/pomodoro/ticket/models.py
import datetime
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.signals import pre_save,post_save
from django.db import models
from django.contrib import auth
from django.dispatch import receiver

# Create your models here.

class Author(auth.models.User):

	class Meta:
		proxy = True

	def lastActions(self,limit=30):
		return Action.objects.filter(author=self).order_by("-time")[0:limit]

	def lastTickets(self,limit=10):
		return Ticket.objects.filter(actions__author=self).distinct().order_by("-actions__time")[0:limit]

	def name(self):
		fullName = self.get_full_name()
		if fullName :
			return fullName
		return self.username

@python_2_unicode_compatible
class TicketCategory(models.Model):
	title = models.CharField(max_length=128,blank=False,null=False,help_text="Esse eh um texto de ajuda")
	description = models.TextField(blank=True)
	color = models.CharField(max_length=6,blank=False,default="777777")

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class TicketFlow(models.Model):
	title = models.CharField(max_length=128,blank=False,null=False)
	description = models.TextField(blank=True)

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class State(models.Model):
	title = models.CharField(max_length=128,blank=False,null=False)
	description = models.TextField(blank=True)
	after = models.ManyToManyField("self",null=True,blank=True,symmetrical=False,related_name="before")
	color = models.CharField(max_length=6,blank=False,default="777777")
	flow = models.ForeignKey(TicketFlow,null=False,blank=False)

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class ActionCategory(models.Model):
	title = models.CharField(max_length=128,blank=False,null=False);
	description = models.TextField(blank=True)
	color = models.CharField(max_length=6,blank=False,default="777777")

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class Ticket(models.Model):
	parent = models.ForeignKey("self",related_name="children",null=True,blank=True)
	related = models.ManyToManyField("self",null=True,blank=True)
	title = models.CharField(max_length=128)
	description = models.TextField(blank=True)
	categories = models.ManyToManyField(TicketCategory,null=False)
	flow = models.ForeignKey(TicketFlow,null=False,blank=False)

	def orderedActions(self):
		return Action.objects.filter(ticket=self).order_by("-time")

	def authors(self):
		return Author.objects.distinct().filter(actions__ticket=self)

	def firstAction(self):
		firstAction = Action.objects.filter(ticket=self).order_by("time")[0:1]
		if len(firstAction) == 1:
			return firstAction[0]
		return None

	def lastAction(self):
		lastAction = Action.objects.filter(ticket=self).order_by("-time")[0:1]
		if len(lastAction) == 1:
			return lastAction[0]
		return None

	def state(self):
		lastStates = TicketState.objects.filter(ticket=self).order_by("-time")[0:1]
		if len(lastStates) == 1:
			return lastStates[0]
		return None

	def color(self):
		state = self.state()
		if state :
			return state.color()
		return "FF0000"

	def __str__(self):
		return self.title

@python_2_unicode_compatible
class TicketState(models.Model):
	author = models.ForeignKey(Author,null=False,blank=False)
	time = models.DateTimeField(auto_now_add=True,editable=False)
	state = models.ForeignKey(State,null=False,blank=False)
	ticket = models.ForeignKey(Ticket,related_name="states",null=False,blank=False)
	description = models.TextField(blank=True)

	def color(self):
		return self.state.color

	def __str__(self):
		return "%s (%s)" % (self.state.title,self.time)

@python_2_unicode_compatible
class Action(models.Model):
	time = models.DateTimeField(auto_now_add=True,editable=False)
	ticket = models.ForeignKey(Ticket,null=False,related_name="actions")
	title = models.CharField("teste",max_length=128,blank=False,help_text="Esse eh um texto de ajuda")
	description = models.TextField(blank=True,help_text="Esse eh um texto de ajuda")
	author = models.ForeignKey(Author,related_name="actions",null=False)
	category = models.ManyToManyField(ActionCategory,null=True,blank=True)

	def __str__(self):
		return self.title

python-server/pomodoro/ticket/forms.py
 # -*- coding: utf-8 -*-
from django.forms import ModelForm
from ticket.models import Action
from ticket.models import Ticket
from django.forms.widgets import SelectMultiple


class BootstrapForm(ModelForm):

	def __init__(self,*args,**kwargs):
		super(ModelForm, self).__init__(*args, **kwargs)
		for field in self:
			print vars(field.field.widget),type(field),type(field.field),type(field.field.widget)
			field.field.widget.attrs["class"] = "form-control"
			if isinstance(field.field.widget,SelectMultiple):
				field.field.widget.attrs["multiselect"] = "showall"
			else:
				field.field.widget.attrs["placeholder"] = field.field.help_text


class ActionForm(BootstrapForm):
	class Meta:
		model = Action
		fields = ["title","description","ticket"]

class TicketForm(BootstrapForm):
	class Meta:
		model = Ticket
		fields = ["title","description","parent","categories"]

python-server/pomodoro/ticket/views.py
 # -*- coding: utf-8 -*-
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages


from ticket.models import Ticket
from ticket.models import TicketState
from ticket.models import Action
from ticket.models import Author

from ticket.forms import ActionForm
from ticket.forms import TicketForm

# Create your views here.
def ping(request):
	if request.method == 'GET':
		form = ActionForm()
	elif request.method == 'POST':
		form = ActionForm(request.POST)
	print form
	for field in form:
		print vars(field)
		print vars(field.field)
		print vars(field.field.widget)
		print "\n"
	return render(request,"form.html",{"form":form})


def newAction(request):
	ticket = get_object_or_404(Ticket,pk=request.POST.get("ticket",-1))
	form = ActionForm(request.POST)
	try:
		action = form.save(commit=False)
	except Exception as e:
		#messages.error(request,str(e))
		return render(request,"action/new.html",{"form":form,"ticket":ticket})
		#return redirect(reverse("ticket:show-ticket",kwargs={"ticketId":1}))
	action.author = Author.objects.get(id=request.user.id)
	action.save()
	messages.success(request,"Iteracao Efetuada com Sucesso!");
	return showAction(request,action.id)


def showAction(request,actionId):
	action = get_object_or_404(Action,pk=int(actionId))
	ticketId = action.ticket.id
	url = reverse("ticket:show-ticket",kwargs={"ticketId":ticketId})
	url += "#action-%d" % action.id
	return HttpResponseRedirect(url)

@login_required
def showAuthor(request,authorName):
	author = get_object_or_404(Author,username=authorName)
	return render(request,"author/detail.html",{"author":author})

@login_required
def home(request):
	author = get_object_or_404(Author,pk=request.user.id)
	return render(request,"author/home.html",{"author":author})

python-server/pomodoro/ticket/templates/ticket/detail.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "ticket/head.html" %}
<div>
	{% if perms.ticket.add_action %}
		{% include "action/new.html" with form=actionForm %}
	{% endif %}
</div>
<div>
	{% for action in ticket.orderedActions %}
		{% include "action/detail.html" %}
	{% endfor %}		
</div>
{% endblock %}

python-server/pomodoro/ticket/templates/ticket/find.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
<table class="table table-striped table-hover" >
	<thead>
		<tr>
			<th class="text-center"></th>
			<th class="text-center">{% trans "ticket.title" %}</th>
			<th class="text-center">{% trans "ticket.state" %}</th>
			<th class="text-center">{% trans "ticket.firstAction" %}</th>
			<th class="text-center">{% trans "ticket.lastAction" %}</th>
		</tr>
	</thead>
	<tbody>
		{% for ticket in tickets %}
		<tr>
			<td>
				{% include "ticket/link.html" %}
			</td>
			<td>
				{{ticket.title}}
			</td>
			<td>
				{{ticket.state}}
			</td>
			<td>
				{% if ticket.firstAction  %}
					{% include "action/link.html" with action=ticket.firstAction %}
					{{ticket.firstAction.time}}
				{% else %}
					---
				{% endif %}
			</td>
			<td>
				{% if ticket.lastAction  %}	
					{% include "action/link.html" with action=ticket.lastAction %}
					{{ticket.lastAction.time}}
				{% else %}
					---
				{% endif %}
			</td>
		</tr>
		{% endfor %}		
	</tbody>
	<tfoot>
		
	</tfoot>
</table>
{% endblock %}

python-server/pomodoro/ticket/templates/ticket/head.html
{% load i18n %}
{% load pomodoro %}
<div class="bs-callout bs-callout-default" style="border-left-color:#{{ticket.color}}" >
	<div class="row">
		<div class="col-xs-6 text-left">
			<h3>
				{% include "ticket/link.html" %}
				{{ticket.title}}	
				<i>
					({{ticket.actions.all | length }})
				</i>	
			</h3>
			{% if ticket.parent %}
			<h5>
				{% include "ticket/link.html" with ticket=ticket.parent %}
				{{ticket.parent.title}}
			</h5>
			{% endif %}
		</div>
		<div class="col-xs-6 text-right">
			<p>{{ticket.firstAction.time}}</p>
			<p>{{ticket.lastAction.time}}</p>
		</div>
	</div>
	<br />
	<pre>{{ticket.description | prepare }}</pre>
	<div class="row">
		<div class="col-xs-4 text-left">
			{% trans "ticket.children" %}
			<a
				href="{% url "ticket:add-child-ticket" ticket.id %}"
				class="btn btn-success btn-xs">
				<span class="glyphicon glyphicon-plus"></span>
			</a>
			<p></p>
			{% for child in ticket.children.all %}
			<p>
				{% include "ticket/link.html" with ticket=child %}
				{{child.title}}
			</p>
			{% endfor %}
		</div>
		<div class="col-xs-4 text-left"></div>
		<div class="col-xs-4 text-left">
			{% trans "ticket.related" %}
			{% for related in ticket.related.all %}
			<p>
				{% include "ticket/link.html" with ticket=related %}
				{{related.title}}
			</p>
			{% endfor %}
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-xs-8"></div>
		<div class="col-xs-4">
			<div class="form-group" >
				<label>{% trans "ticket.state" %}</label>
				<select class="form-control" name="state" >
					<option value="ticket.state.state.id" >
						{{ticket.state.state}}
					</option>
					{% for state in ticket.state.state.after.all %}
					<option value="{{state.id}}" >
						{{state}}
					</option>
					{% endfor %}
				</select>
			</div>
		</div>
	</div>
	<div class="row" >
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<div class="row" >
		<div class="col-xs-6 text-left" >
			{% for author in ticket.authors %}
				{% include "author/link.html" %}
			{% endfor %}
		</div>
		<div class="col-xs-6 text-right" >
			{% for category in ticket.category.all %}
				{% include "ticket-category/link.html" %}
			{% endfor %}
		</div>
	</div>
</div>

python-server/pomodoro/ticket/templates/ticket/link.html
<a
	title
	data-toggle="tooltip"
	data-original-title="{{ticket.title}}"
	href="{% url "ticket:show-ticket" ticket.id %}"
	class="label label-{{ labelType|default:"default" }}"
	style="background-color:#{{ticket.color}};"
	>#{{ticket.id}}</a>

python-server/pomodoro/ticket/templates/ticket/new.html
{% extends "base.html" %}
{% load pomodoro %}
{% load i18n %}
{% block body %}
<div class="bs-callout bs-callout-info" >
	<form role="form" method="POST" action="{% url "ticket:new-ticket"%}">
		{% csrf_token %}
		<div class="row">
			<div class="col-xs-6">
				<div class="form-group">
					{{form.title.label_tag}}
					<div class="input-group">
						<div class="input-group-addon"><b>#</b></div>
						{{form.title}}
					</div>
				</div>
				{% if parent %}
				<h5>
					<input type="hidden" name="parent" value="{{parent.id}}" />
					{% include "ticket/link.html" with ticket=parent %}
					{{ parent.title }}
				</h5>
				{% endif %}
			</div>
			<div class="col-xs-6"></div>
		</div>
		<br />
		<div class="row">
			<div class="col-xs-12">
				<div class="form-group"> 
					{{form.description.label_tag}}
					{{form.description}}
				</div>
			</div>
		</div>
		<div class="row" >
			<div class="col-xs-12">
				<div class="form-group">
					{{form.categories.label_tag}}
					{{form.categories}}
				</div>
			</div>
		</div>
		<div class="row" >
			<div class="col-xs-6">
			</div>
			<div class="col-xs-6 text-right">
				<button class="btn btn-success" type="submit" >
					<span class="glyphicon glyphicon-ok"></span>
				</button>
			</div>
		</div>
	</form>
</div>
{% endblock %}