python-server/pomodoro/menu/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pomodoro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r"^ticket/", include("ticket.urls")),
]

python-server/pomodoro/pomodoro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pomodoro.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r"^$", "pomodoro.views.home", name="home"),
	url(r"^accounts/login/$","pomodoro.views.login",name="login"),
	url(r"^accounts/logout/$","pomodoro.views.logout",name="logout"),
    url(r"^root/", include(admin.site.urls)),
    url(r"^ticket/", include("ticket.urls",namespace="ticket")),
]

python-server/pomodoro/ticket/urls.py
from django.conf.urls import include, url
from ticket import views
from ticket import tickets

urlpatterns = [
	url(r"^ping/",views.ping,name="ping-pong"),
	url(r"^home/",views.home,name="home"),

	url(r"^$",tickets.find,name="find-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/$",tickets.show,name="show-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/child/$",tickets.addChild,name="add-child-ticket"),
	url(r"^(?P<ticketId>[0-9]+)/interact/$",tickets.addAction,name="add-action-ticket"),
	url(r"^new/$",tickets.new,name="new-ticket"),

	url(r"^action/(?P<actionId>[0-9]+)/$",views.showAction,name="show-action"),
	url(r"^action/new/$",views.newAction,name="new-action"),
	url(r"^author/(?P<authorName>[a-zA-Z0-9]+)/$",views.showAuthor,name="show-author"),
]

python-server/pomodoro/pomodoro/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import auth

# Create your views here.
def home(request):
	return render(request,"admin.html");

def login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = auth.authenticate(username=username,password=password)
		if user is not None and user.is_active:
			auth.login(request,user)
			return HttpResponseRedirect(request.GET.get('next',reverse("home")))

	return render(request,"login.html")

def logout(request):
	auth.logout(request)
	return render(request,"home.html")

python-server/pomodoro/pomodoro/templates/admin.html
{% extends "base.html" %}
{% block body %}
<div id="main">
    <div id="main-menu">
        {% block menu %}
        {% endblock %}
    </div>
    <div id="main-content">
        {% block content %}
        <iframe
            id="browser"
            class="iframe"
            seamless=""
            style="width:100%;height:100%"
            frameBorder="0"
            scrolling="no"
            onload='javascript:resizeIframe(this);'
            src="{% url "ticket:ping-pong" %}">
        </iframe>
        {% endblock %}
    </div>
</div>
{% endblock %}

python-server/pomodoro/pomodoro/templates/base.html
{% load pomodoro %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>
        {% block title %}
            Pomodoro
        {% endblock %}
        </title>
        <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
        <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
        <script type="text/javascript" src="{% static "js/pomodoro.js" %}"></script>
        <script type="text/javascript" src="{% static "js/multiselect.js" %}"></script>
        <script type="text/javascript" src="{% static "js/mousetrap.js" %}"></script>
        <script type="text/javascript" src="{% static "js/jquery.form.js" %}"></script>
        <link rel="stylesheet" href="{% static "css/pomodoro.css" %}" />
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
        <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}" />
        <link rel="stylesheet" href="{% static "css/bootstrap-doc.css" %}" />
        <link rel="stylesheet" href="{% static "css/multiselect.css" %}" />
        <link rel="icon" type="image/png" href="{% static "favicon.png" %}" />
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            {% block navbar %}
            <div class="container-fluid">
               <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url "home" %}">Pomarola</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url "ticket:find-ticket" %}">Tickets</a>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-right" role="search" method="GET">
                        <div class="form-group">
                            <div class="input-group">
                                <input name="q" type="text" class="form-control" placeholder="Busca Rapida" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            {% endblock %}
        </nav>
        <div class="row-fluid">
            <div class="col-xs-1"></div>
            <div class="col-xs-10">
                {% block body %}
                {% endblock %}      
            </div>
            <div class="col-xs-1"></div> 
        </div>
        {% if messages %}
        <div class="messages text-center">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags | msgClass }}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </body>
</html>

python-server/pomodoro/pomodoro/templates/fields.html
{% for field in fields %}
	<div class="form-group{% if field.errors %} has-error {% endif %}">
		{{field.label_tag}} {{field}}
		<div class="help-block">
			{% for error in field.errors %}
				{{error}}
			{% endfor %}
		</div>
	</div>
{% endfor %}

python-server/pomodoro/pomodoro/templates/form.html
{% extends "base.html" %}
{% block body %}
<form class="form" method="POST">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
	{{ hidden }}
{% endfor %}
{% include "fields.html" with fields=form %}
	<br />
	<button class="btn btn-success" type="submit">
		Send
	</button>
</form>
{% endblock %}

python-server/pomodoro/pomodoro/templates/login.html
{% extends "base.html" %}
{% block body %}
<div class="jumbotron">
	<div class="container">
		<div class="row" >
			<div class="col-xs-1"></div>
			<div class="col-xs-10">
				<form role="form" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label>
							Login
						</label>
						<input name="username" type="text" class="form-control" placeholder="Username or email" />
					</div>
					<div class="form-group">
						<label>
							Senha
						</label>
						<input name="password" type="password" class="form-control" />
					</div>
					<button type="submit" class="btn btn-default">
						Login
					</button>
				</form>
			</div>
			<div class="col-xs-1"></div>
		</div>
	</div>
</div
{% endblock %}